Showndarya/Hacktoberfest

test5.txt

add test5.txt

---

H/Hard.json

Issue #25 
Added "H" folder and "Hard.json"

Adding word: "Hard"

---

P/Perfect.json

Added "P" folder and "Perfect.json"

---

U/Ugly.json

Added U folder for Ugly

---

E/Easy.json
E/Evil.json
H/Hack.json
H/Host.json

Add words with H, Issue #25

---

C/Contribute.json
I/Influence.json

Description:
Added new files for the words 'Influence' & 'Contribute'

Issue: #25 Added 'influence' and 'Contribute' words

---

V/Volatile.json

The Pull Request resolves Issue #37 
Description:
`V` folder created along with the `Volatile.json` file inside of it.

Adding 'Volatile' word

---

S/Shard.json

The Pull Request resolves Issue #39 
Description:
Made a new `S` folder and added a definition for the word `Shard`.

adding Shard

---

W/Welter_noun.json
W/Welter_verb.json
Z/Zealot.json

The Pull Request resolves Issue #41
Description:
Added the verb and noun version of `Welter`

Welter added

---

W/Whimsical.json

The Pull Request resolves Issue #47
Description:
Added the term `Whimsical`

Added Whimsical

---

Y/Yarn.json

The Pull Request resolves Issue #51
Description:
Added the term `Yarn`.

Added Yarn

---

A/Ambush.json

Added ambush to the folder for A. Also added the definition of ambush and the part of speech.

Added Ambush

---

F/Fabel.json

Description:
- Added F folder
- Added Fabel.json inside F folder.

added Fable to F folder.

---

G/gambit.json
G/garrulous.json
G/gawk.json
G/genesis.json
G/gentility.json
G/gingerly.json
G/gist.json
G/git.json
G/glimmer.json
G/glossary.json

words added -- gambit, garrulous, gawk, genesis, genetility, gingerly, gist, git, glimmer, glossary
The Pull Request resolves Issue #59 
Description:
words added -- gambit, garrulous, gawk, genesis, genetility, gingerly, gist, git, glimmer, glossary

Add words starting with letter 'G' #59

---

J/Jaguar.json
J/Javascript.json

The Pull Request resolves Issue #[62]
Description:
New Directory `J` with 2 words

directory J - words Jaguar Javascript

---

A/Ambiguous.json
C/Client.json
C/Commit.json
F/Feasible.json
F/Furious.json
M/Minute_adjective.json
M/Minute_noun.json
O/Open-source.json
O/Optimistic.json
U/Unanimous.json
V/Versatile.json

I Have some New Words,created some new Folders like 'F' as #58,and for letter 'O' .

Added new Words and new Letters.

---

F/Friend_noun.json
F/Friend_verb.json

Description:
Added Friend as the verb and noun.

Added Friend

---

F/Fear_noun.json
F/Fear_verb.json
F/Feast_noun.json
F/Feast_verb.json

Description:
Added Feast as the verb and noun.

Added Feast

---

F/Frizzle_noun.json
F/Frizzle_verb.json

Description:
Added Frizzle as noun and verb.

Added Frizzle

---

D/Discrimination.json

Description:
Created the D word folder and added Discrimination.

Added Discrimination

---

L/Lavish.json

added 'Lavish' word

---

Q/Queue.json

Description:
- Add `Q` folder
- Add `Queue` word

Add Q folder and Queue word

---

A/Anecdote.json

Added Anecdote

---

E/Egg.json

#25 Add word "Egg"

---

D/Dream_noun.json
D/Dream_verb.json

Description:
Noun and verb added of Dream.

Add Dream word

---

Q/Quality.json

#72 
**Description**:
Added the word quality and definitions

add quality.json

---

D/Dead.json
D/Duplicate.json

resolve issue: https://github.com/Showndarya/Hacktoberfest/issues/57

Added a word starting from D

---

D/Density.json

Added Density

---

Q/Queen.json

add Queen-json

---

A/Alchemy.json

Description:
Added new word alchemy

Added alchemy.json

---

D/Depth.json

Description:
Noun added for the word Depth

Added word Depth

---

Q/Quarrel.json

add quarrel.json

---

D/Develop.json

Description:
Added Develop word

Added Develop

---

Q/Quack.json

add quack.json

---

D/Determine.json

Description:
Added Determine word

Added Determine

---

D/Dose_noun.json
D/Dose_verb.json

Description:
noun and verb added for the word Dose

Added word Dose

---

Q/Qabalistic.json

add qabalistic.json

---

G/Gas.json
G/Gravel.json

Description:
Added definitions for Gas and Gravel

#59 Add Gas, Gravel

---

N/Nimble.json

Description:
I have created the N folder and added the definition of the word 'Nimble'

Added N folder and added the word Nimble

---

G/genetics.json

The Pull Request resolves Issue #54 
Description:
Added G word "Genetics"

#54 added genetics

---

N/Nebula.json
N/Nexus.json

Description: 
Added definitions for Nexus and Nebula

# 107 Add: Nexus.json, Nebula.json

---

C/Crevasse.json

The Pull Request resolves Adding a word
Description:
I have added the word crevasse

added the word crevasse

---

K/King.json
K/Knight.json

Description:
Add definitions for King and Knight

#93 Add: King.json, Knight.json

---

K/Kitten.json
K/Kooky.json

Add Kitten, Kooky

---

N/Navy.json
N/Necessary.json

added new words

---

T/Table.json
T/Tail.json
T/Tall.json
T/Team.json

Description:
I added the words Table, Tail, Tall and Team under the T/ folder. People can add more :)

Add Table, Tail, Tall and Team under T/ (#121)

---

I/Incredible.json

created Incredible.json

---

D/Dilapidated.json

Added word 'dilapidated' to D folder.

---

N/Name.json
N/Name_adjective.json
N/Name_noun.json
N/Name_verb.json

The Pull Request resolves Issue #[107]
Description:
Added N, and 'name'. Please check if the specified format is valid.

Created a folder for "N" and added a word.

---

Y/yearling.json

The Pull Request resolves Issue #[51]
Description:

added yearling

---

A/Ancestor.json
A/Apology.json

Description:
Added new words to A.

Added words to A

---

N/Nasty.json
N/Notorious.json

Description:
Added words Nasty and Notorious to the N folder.

Add words 'Nasty' and 'Notorious' to N folder.

---

G/Genocide.json

The Pull Request resolves Issue #59
Description:
Adds word and definition for Genocide

Add: Genocide.json

---

Q/Quote.json
V/Vagabond.json

Description:
Added 'Quote' to Q folder.

Add 'Quote' to Q folder.

---

R/Retire.json

Added Retire.json

---

Z/Zenith.json

The Pull Request resolves Issue #139
Description:
Added the word Zenith

Added Zenith

---

T/train.json

Description:
I added a new word to the project.

Added train.json

---

I/Infinity.json

Added Infinity.json

---

C/Chicanery.json

The Pull Request resolves Issue #137

Add Chicanery.json

---

X/Xenophobe.json
X/Xenophobia.json

The Pull Request resolves Issue #140

Add the words 'xenophobe' and 'xenophobia' to the X folder.

---

T/Talent.json
T/Top.json
T/Torch.json
T/Trace.json

The Pull Request resolves Issue #121
Description:
I created 4 .json files containing diferent words for your repository!!

Insertion of Talent, Top, Torch and Trace

---

R/Recluse_adjective.json
R/Recluse_noun.json

The Pull Request resolves Issue #149 
Description:
Added recluse files and definitions for noun and adjective.

Added Recluse noun and adjective definitions

---

A/across.json
D/Deboss.json

Description:
Added Across and Deboss
* The #146  should be replaced with the specific Issue being referenced.

Adding Across, Deboss

---

D/Deprecate.json

Description:
Added deprecate to the d folder

add deprecate.json to 'D' folder

---

F/Floss.json
L/Loss.json
M/Moss.json

The Pull Request resolves Issue #146 
Loss, Moss, Floss
Description:

More Word with 'oss'

---

G/Gloss.json
G/Gross_adjective.json
G/Gross_noun.json

The Pull Request resolves Issue #146 
Description:
Added gross and gloss

Added gross and gloss

---

L/Lexemic.json

Added new word 'Lexeme'

---

I/Incross.json
K/Kaross.json

The Pull Request resolves Issue #146

Added Incross and Kaross

---

E/Eager.json
E/Emoji.json
E/Empathy.json
E/Enclosure.json

I added a couple of words in the E folder and capitalized them.

Added word to E folder.

---

A/Altitude.json

Add "Altitude"

---

D/Dross.json
T/Toss.json

The Pull Request resolves Issue #146

Created Toss and Dross

---

Y/Yuppie.json

The Pull Request resolves Issue #51 
Description:
Add "Yuppie"

Add "Yuppie"

---

D/Decadent.json

Add "decadent"

---

F/Fructose.json

Add "Fructose"

---

G/Gerrymander.json

The Pull Request resolves Issue #59
Description:
Add "Gerrymander"

Add "Gerrymander"

---

T/Tolerate.json
T/Transfer.json

Added tranfer and tolerate

---

B/Blatantly.json
E/Effusive.json
O/Ossify.json

The Pull Request is to create new words
Description:
Addition of new words

Adding words

---

H/Hemophilia.json
N/Narcissist.json

The Pull Request to add couple of more words
Description:
Adding Hemophilia and Narcissist

Adding new words

---

E/Evasive.json
V/Vicinity.json

evasive added

---

F/Fanatic_adjective.json
F/Fanatic_noun.json

The Pull Request resolves Issue #190
Description:
From the commit message: "Added the definition of the word - Fanatic (adjective, noun)"

Added the definition of the word - Fanatic (adjective, noun)

---

F/Faff.json

Description:
- Committing the word [Faff](https://www.dictionary.com/browse/faff)

Commit of the word Faff

---

Q/Quintessential.json

The Pull Request resolves Issue #200 
Description :
Added `Quintessential.json` to the list of words

Added word Quintessential

---

K/Kerfuffle.json

Add Kerfuffle

---

A/appal.json
A/appalling.json

added the .json files for appal and appalling

Pull request resolves issue #201

---

A/Appal.json
A/Appalling.json
J/Jacket.json

Added the definitions and parts of speech of the words - Appal and Appalling using Appal.json and Appalling.json respectively.

added Appal.json and Appalling.json

---

C/Capricious.json
C/Corroborate.json
E/Ephemeral.json

Added some words from #180 
- Ephemeral
- Capricious
- Corroborate

Added Capricious, Corroborate and Ephemeral word

---

C/Community.json
F/Fun.json
S/Sad.json

add Community, Fun & Sad word

---

J/Jeopardy.json
J/Journey.json

#62 
Add words:
- Journey
- Jeopardy

Add Journey and Jeopardy

---

P/pragmatic.json

The Pull Request resolves Issue #180 
Description:
Added pragmatic.json.

Created pragmatic.json

---

A/ambivalent.json
P/pragmatic.json

The Pull Request resolves Issue #180 
Description:
Added ambivalent.json

Created ambivalent.json

---

U/Ubiquitous.json

Added a new word Ubiquitous

---

E/Eloquence.json
E/Eloquent.json

The Pull Request resolves Issue #218

Added Eloquence and Eloquent json files

---

M/Misogynist.json
M/Misogyny.json

The Pull Request resolves Issue #217
Description:
Add words Misogyny and Misogynist.

add Misogyny and Misogynist word definition (#217)

---

B/Belligerence.json
B/Belligerent.json
M/Mercurial.json
R/Reticence.json
R/Reticent.json

The Pull Request resolves Issue #180
Description:
Added the words: Belligerence, Belligerent, Mercurial, Reticence, and Reticent

#180 Add Belligerence, Belligerent, Mercurial, Retirence, and Retirent

---

C/Complacent.json
C/Complaisant.json

The Pull Request resolves Issue #226 
Description:
Added words complacent and complaisant

Complacent and Complaisant

---

A/Abbreviate.json

Added abbreviate

---

A/Accurate.json

added accurate

---

A/Affectionate.json

Description:
Added affectionate

added affectionate

---

A/Approximate.json

Description:
Added Approximate

added approximate

---

U/Ultimate_Adjective.json
U/Ultimate_Noun.json

Define Ultimate

---

F/Felicitate.json

Description:
Added the word 'felicitate', although it was not in the list.

Added the word 'felicitate'

---

A/Appropriate.json

Description:
Added Appropriate

added appropriate

---

P/Private_adjective.json
P/Private_noun.json

Description:
Added Private, both in Noun and Adjective form.

Added Private

---

E/Enervate_adjective.json
E/Enervate_verb.json
E/Erudite.json
E/Esoteric.json

add Esoteric, Enervate (both verb and adj) and Erudite to issue#180

---

C/Certificate.json
C/Climate.json
C/Considerate.json
S/Sanguine.json

Climate, Considerate and certificate

---

O/Optimist.json
P/Pessimist.json
P/Pessimistic.json

The Pull Request resolves Issue #235 
I've just added requested words. Have a great day!

add 'Optimist', 'Pessimist' and 'Pessimistic'

---

R/Random_adjective.json
R/Random_noum.json

Description:
Add the word Random

Add Random word

---

E/Equilibrium.json
E/Equipoise_noun.json
E/Equipoise_verb.json

The Pull Request resolves Issue #244 
Description:
add equilibrium and equipoise (noun & verb)

feat: add equilibrium and equipoise (noun & verb) #244

---

B/Benevolent.json
M/Malignant.json

The Pull Request resolves Issue #242 
Description:
Added files for words "Benevolent" and "Malignant"

#242 - Add words "Benevolent" and "Malignant" 

---

R/Rancorous.json

The Pull Request resolves Issue #243 
Description:
Added file for word Rancorous

#243 - Added word Rancorous

---

D/Deliberate.json
D/Desperate.json

Added desperate and deliberate

---

G/galaxy.json
G/glacier.json
G/graph.json

The Pull Request resolves Issue #59 
Description:
Added the words Galaxy,Graph and Glacier

Added Galaxy,Graph and Glacier

---

P/Passionate.json

Description:
Added `Passionate.json`

Passionate

---

A/Aroma.json
T/Tang.json

The Pull Request resolves Issue #252 
Description:
add Aroma and Tang. 
Petrichor is already exist.

add Aroma Tang PR#252

---

M/Moderate_verb.json

Description:
Added moderate_verb description

moderate-verb

---

E/Exaggerate.json

Description:
Added exaggerate definition

Add exaggerate definition

---

P/Profound_adjective.json
P/Profound_noun.json
S/Superficial.json

The Pull Request resolves Issue #266 
Description:
Added profound_noun, profound-adjective, and superficial.

Added profound_noun, profound-adjective, and superficial

---

C/Consolidate.json

Add consolidate definition

---

K/Kangaroo.json

Description:
Added Kangaroo.json

Added Kangaroo

---

A/Accumulate.json
A/Appreciate.json
D/Disproportionate.json

Description:
Added These words:
Disproportionate
Appreciate
Accumulate

Added Disproportionate,Appreciate,Accumulate

---

C/Coss.json
P/Pencil.json

The Pull Request resolves Issue #146 
Description:
added coss

added coss

---

C/Coss.json
N/Neck.json
P/Pencil.json

The Pull Request resolves Issue #107 
Description:
added the word Neck

Added Neck

---

T/Travel.json

Issue #273

---

C/Compensate.json
C/Coss.json
N/Neck.json
P/Pencil.json

Description:
Added the word compensate

Added compensate

---

E/Expedition.json

add expedition definition

---

C/Compensate.json
C/Coss.json
D/Destiny.json
N/Neck.json
P/Pencil.json

Description:
Added the word Destiny

Added Destiny

---

V/Voyage.json

Description:
Add voyage definition

Add voyage definiton

---

F/Fly_noun.json
F/Fly_verb.json

The Pull Request resolves Issue #273
Description:
Added the word Fly.

Word Fly added

---

A/Anonymous.json
C/Compensate.json
C/Coss.json
D/Destiny.json
N/Neck.json
P/Pencil.json

Description:
Added the word Anonymous

Added Anonymous

---

T/Travel_Noun.json

The Pull Request resolves Issue #290 
Adds the noun form definition of the word Travel

Add travel noun form json

---

W/wanderlust.json

The Pull Request resolves Issue  #273
Description:
added the word "wanderlust" to the category "W"

added wanderlust

---

E/Ecstatic.json

Added Ecstatic

---

C/Cross.json

The Pull Request resolves Issue #146 
Description:
Added Cross.json

added Cross

---

O/Oblivious.json
P/Plethora.json

I added 2 new words to the repo

2 new words added

---

C/Credulity.json
C/Cynicism.json

The Pull Request resolves Issue #298 
Description:
Added words Credulity and Cynicism
Added all the definitions of Credulity in a file named Credulity.json
Added all the definitions of Cynicism in a file named Cynicism.json

Add words "Credulity" and "Cynicism"

---

C/Conviction.json
S/Scepticism.json

The Pull Request resolves Issue #297 
Description:
Added the files for conviction and scepticism

added Conviction and Scepticism

---

K/Knot.json

Description:
Add Knot to K folder

Add knot to K

---

Q/Quail.json

The Pull Request resolves Issue #72 
Description:
Add Quail to Q folder

Add quail to Q

---

T/Tortoise.json

Description:
Add Tortoise to T folder.

Add tortoise to T

---

Q/Quake_noun.json
Q/Quake_verb.json
Q/Quaver_noun.json
Q/Quaver_verb.json
Q/Quiver_noun.json
Q/Quiver_verb.json

The Pull Request resolves Issue #303 
Description:
Add Quake Quaver Quiver

Add Quake Quaver Quiver

---

V/Vigour.json
V/Vitality.json
V/Vivacity.json

The Pull Request resolves Issue #306  
Description:
Add Vigour Vitality Vivacity

Add Vigour Vitality Vivacity

---

W/Wander_noun.json
W/Wander_verb.json

The Pull Request resolves Issue #273   
Description:
Add Wander

Add wander

---

F/Flabbergast.json

Description:
Added `Flabbergast` to the list.

added flabbergast to the list

---

B/Breastie.json

Add new word on B letter

---

T/temple.json

added temple.json

---

N/nausea.json

added nausea.json

---

K/karma.json

added karma.json

---

N/Nostalgia.json

The Pull Request resolves Issue #107 
Description:
Added Nostalgia.json in accordance with format

Add nostalgia

---

S/superstimulate.json

added superstimulate

---

F/flunkey.json
F/flunky.json

added flunkey.json

---

B/Baffle.json
B/Befuddle.json
B/Bemused.json

The Pull Request resolves Issue #329 
Description:
Added Befuddle, Bemused, and Baffle

Befuddle, Bemused, and Baffle

---

P/Peregrinate.json

Add Peregrinate

---

B/Benediction.json
B/Benefactor.json
B/Beneficiary.josn

The Pull Request resolves Issue #325 
Description:
Added words "Benediction", "Benefactor" and "Beneficiary" in files "Benediction.json", "Benefactor.json" and "Beneficiary.json".

Added words "Benediction", "Benefactor" and "Beneficiary"

---

A/Articulate.json
A/Astute.json
B/Blink.json
D/Dude.json
M/Morbid.json
O/Owl.json
W/Write.json

Description:
new words for articulate, astute, blink, dude, morbid, owl, write

articulate, astute, blink, dude, morbid, owl, write

---

Q/Qualify.json
Q/Quandong.json
Q/Quant.json
Q/Quantum.json

Description:
Adding Qualify, Quandong, Quant and Quantum

Adding Qualify, Quandong, Quant and Quantum

---

A/Abstract.json
B/Bashful.json
C/Cruel.json
D/Depreciate.json
E/Ego.json

Add: 
- Astract.json --- the adjective definition of Abstract 
- Bashful.json --- the adjective definition of Bashful
- Cruel.json --- the adjective definition of Cruel
- Depreciate.json -- the verb definition of Depreciate
- Ego.json -- the noun definition of Ego

add Abstract.json

---

A/Android.json

contributing to https://github.com/Showndarya/Hacktoberfest/issues/52

Add Android.json

---

D/Dad.json
D/Democracy.json
D/Dynamic.json

Add new words to the dictionary #[1]
Description:
I've added 3 more words starting with D, Democracy, Dad, Dynamic

Adding words Democracy, Dad, Dynamic

---

T/Transit_Noun.json
T/Transit_Verb.json

The Pull Request resolves Issue https://github.com/Showndarya/Hacktoberfest/issues/273
Description:
Added definitons for the Word: Transit

Add definitions for word Transit

---

Y/Yottabyte.json

The Pull Request resolves Issue #51 
Description:
I added the word "yottabyte" to the Y folder.

Add Yottabyte

---

K/Kneel.json
K/Knell.json
K/Knoll.json
K/kneel.json

The Pull Request resolves Issue #337 
Description:
Added words and definitions of "Kneel" , "Knell" and "Knoll" in Kneel.json , Knell.json , Knoll.json respectively.

Added New words Kneel , Knell , Knoll

---

A/Ancient.json
E/Epoch.json
I/Immemorial.json
R/Remove.json
Y/Yore.json

Add Remove.json

---

C/Courtship.json
D/Duration.json
E/Era.json
E/Ere.json

The Pull Request resolves Issue #358 
Description:
Added words "Duration" , "Era" , "Ere" , "Courtship" , their definitions and part of speech in files Duration.json , Era.json ,Ere.json and Courtship.json respectively.

Added Duration.json , Era.json , Ere.json , Courtship.json

---

F/Flaccid.json

Flaccid.json

---

B/Bucolic.json
R/Rustic.json
Y/Yokel.json

The Pull Request resolves Issue #354
Description:
Add Yokel.json, Rustic.json, Bucolic.json

add Yokel.json, Rustic.json, Bucolic.json (closes #354)

---

S/Service.json

service word file

---

G/glue.json

The Pull Request resolves Issue #59 
Description:
added glue

Added glue.json

---

A/Alpha.json
A/Alphabet.json
A/Automation.json

The Pull Request contributes to Issue #52

add Alpha, Alphabet, Automation

---

A/Abstain.json
A/Alcohol.json
F/Festival.json
P/Party.json
P/Periodic.json

Abstain, Alcohol, Festival, Party and Periodic

Added five new word

---

Q/Qi.json

add qi.json

---

D/Dry.json
E/Empty.json
J/Jump.json

add word start e & j

---

A/Anxiety.json
C/Consternation.json
D/Disquietude.json
P/Perturbation.json

Add 4 words for issue #363

---

W/Weary_adjective.json
W/Weary_verb.json

Description:
Add Weary_adjective.json and Weary_verb.json

add Weary.json

---

N/Navigate.json

Description:
Added definition for the Word: Navigate

add definition for navigate

---

F/Fugacious.json
I/Imbroglio.json
L/Lilt_Noun.json
L/Lilt_Verb.json

The Pull Request resolves Issue #58, #353
Description:
Added words starting in F and I

added: Fugacious, Imbroglio, Lilt (Noun and Verb)

---

K/Karaoke.json
K/Knob.json
K/Knowlegdeable.json

The Pull Request resolves Issue #93
Description:
- Adds words: `Knowledgeable, Knob, Karaoke`

add words starting with K

---

K/Karaoke.json
K/Knob.json
K/Knowlegdeable.json
T/Technology.json
T/Temperature.json
T/Template.json

The Pull Request resolves Issue #121
Description:
- Adds words: `Template, Technology, Temperature`

Add words starting with t

---

Q/Quarter.json
Q/Questionnaire.json
Q/Quit.json

Description:
- Adds words: `Quit, Questionnaire, Quarter`

add words starting with Q

---

F/Carry.json
F/Furry.json

The Pull Request resolves Issue #356
Description:
- add words: `Furry, Carry`

add words ending with ry

---

K/Katana.json

Katana.json

---

I/Ideology.json
I/Illness.json
I/Impatient.json
I/Impossible.json
I/Improve.json

The Pull Request resolves Issue #353 
Description:
I am added some I wods.
- Impossible.
- Ideology.
- Improve.
- Illness.
- Impatient.

Adding I words

---

I/Intellectual.json

Intellectual.json

---

M/Mysterious.json

Mysterious.json

---

M/Merge.json

Add merge.json

---

J/Jabber_noun.json
J/jabber_noun.json

Added word Jabber in J folder.
Issue - #62

Added jabber noun #62

---

J/Jabber_noun.json
J/Jabber_verb.json
J/jabber_noun.json

Added word Jabber (verb)
Issue - #62

Added jabber verb #62

---

O/Obstacle.json

Add obstacle noun

---

D/Demeanour.json

Demeanour added

---

D/Drug.json

Added drug #57

---

K/Ketamine.json

Added ketamine #93

---

O/Obnoxious.json
O/Obtrude.json
O/Odious.json

The Pull Request resolves Issue #[397]
Description:
Words are added

Obnoxious, Obtrude and Odious added

---

B/Beguile.json
E/Entrance.json
R/Ravishing.json

The Pull Request resolves Issue #400

add ravishing, entrance & beguile

---

C/Cry_noun.json
C/Cry_verb.json

The Pull Request resolves Issue
#356 
Description:
Add definitions for the word `cry`

add cry definitions

---

M/Marijuana.json

Added Marijuana #407

---

A/Accuracy.json
B/Bureaucracy.json
C/Contingency.json
C/Currency.json
D/Delicacy.json
D/Despondency.json
D/Diplomacy.json
I/Idiocy.json
L/Legacy.json
L/Legitimacy.json
S/Supremacy.json
T/Theocracy.json

The Pull Request resolves Issue #406 
Description:
Added all the words mentioned in issue #406

Added words ending with 'cy'

---

O/Objectionable.json
O/Offend.json
O/Outburst.json

Closes : https://github.com/Showndarya/Hacktoberfest/issues/399

Add Defintions Offend,Outburst,Objectionable

---

I/Interest.json

The Pull Request resolves Issue #353 
Description:
Added the definition for the word 'interest'

Added Interest definition

---

D/Drive.json
D/Drudgery.json
E/Effort.json
E/Excursion.json
E/Exertion.json
P/Position.json
P/Post.json
S/Slog.json
S/Spadework.json
T/Toil.json
T/Trade.json
V/Vocation.json

The Pull Request resolves Issue #364 
Description:
Added remaining words from the list related to the `Work`

Added remaining words related to 'Work'

---

.travis.py
A/Abbreviate.json

It works now you can safely merge
Side note: I used python as it allows to do everything we need without any third party libs or anything like that which makes for a faster travis boot time and execution time, and also the relative ease of python makes it perfect for newcommers to contribute

🚨fix travis 🚨

---

C/Carnival.json
C/Celebrate.json

The Pull Request resolves Issue #417 
Description:
Add definitions of Carnival and Celebrate.

Added Carnival word #417

---

C/Cautionary.json

Description:
Added a word ending in `ry` - `Cautionary`.

adding Cautionary

---

M/Magnet.json

Description:
Add definition of Magnet word.

Added Magnet word #407

---

C/Cavalcade.json
E/Eisteddfod.json
E/Extravaganza.json
F/Fete.json
F/Fiesta.json
J/Jamboree.json

The Pull Request resolves Issue #417 
Description:
fete, fiesta, jamboree, cavalcade, extravaganza and eisteddfod added

fete, fiesta, jamboree, cavalcade, extravaganza and eisteddfod added

---

A/Ambition.json

Description:
Added a new word: Ambition

added a new word Ambition

---

T/Tap.json
T/Target.json
T/Task.json

Description: Added words Tap, Task and Target

Adding words Tap, Target, Task

---

M/Modulate.json

Description:
Add word modulate

Add word modulate

---

.travis.py

check first letter of basename not path

---

Y/Year.json
Y/Yellow.json
Y/Yourself.json
Y/Youth.json

The Pull Request resolves Issue #51
Description:
adds Year, Yellow, Yourself and Youth

adds Year, Yellow, Yourself and Youth

---

N/Narrate.json

added narrate

---

N/Naive.json

added naive

---

M/Median.json

Description:
Corrected the word median

Corrected the word median

---

M/Mosque.json

add word mosque

---

A/Aforementioned.json

Description:
Added word `Aforementioned`

 add aforementioned 

---

G/Giraffe.json
R/Read.json

Add Giraffe and Delete Read

---

U/Unfeigned.json

Added unfeigned

---

U/Ultimatum.json
U/Umbrage.json

The Pull Request resolves Issue #452 
Description:
Added words Ultimatum and Umbrage

Ultimatum,Umbrage

---

U/Unctuous.json

Description:
Added the word unctuous with it's meaning to the dictionary.

Adding unctuous to dict

---

U/Unassailable.json
U/Undulating.json

Description:
Add unassailable and undulating to dictionary!

Add unassailable and undulating.

---

E/Explanatory.json

The Pull Request resolves Issue #356

Explanatory

---

I/Idiosyncrasy.json

The Pull Request resolves Issue #353
Description:
Added definitions of 353

Added Idiosyncrasy definitions

---

U/Unequivocal.json

Add unequivocal

---

C/Cemetery.md

The Pull Request resolves Issue #356
Description:
Add Cemetery

Add Cemetery

---

C/Cruise_noun.json
C/Cruise_verb.json

Description:
Add json definitions for Cruise as a verb and a noun.

add word Cruise_noun and Cruise_verb

---

N/Narcotic.json
N/Nemesis.json
N/Nepotism.json
N/nemesis.json

added nemesis

---

K/Kaleidoscope.json
K/Kilobyte.json
K/Knapsack.json
K/Koala.json

Description:
Kaleidoscope
Kilobyte
Knapsack
Koala
added to dictionary

Added Kaleidoscope, Kilobyte, Knapsack, and Koala

---

Z/Zaitech.json

Adding Zaitech to the Dictionary

Adding Zaitech

---

M/Miscellaneous.json

Added Miscellaneous

---

D/Disc.json

Description:
Added the word "Disc" to the "D" folder.

Adding Disc

---

U/Unerring.json

The Pull Request resolves Issue #452 
Description:
Adding Unerring word

Adding Unerring word

---

N/Nifty.json

The Pull Request resolves Issue #107 
Description:
added nifty.

added nifty

---

Q/Quirk.json

Description:
Added Q/Quirk.json

Added Quirk

---

H/Halcyon.json
L/Lucid.json
P/Phlegmatic.json
P/Placid.json
T/Tranquil.json

Description:
Added words Lucid, Placid, Halcyon, Phlegmatic and Tranquil.
Issue #482

Added words Lucid, Placid, Halcyon, Phlegmatic and Tranquil

---

C/Consignment.json
P/Pigeonhole.json

The Pull Request resolves Issue #481
Description:
Added words Consignment and Pigeonhole.

Added words Consignment and Pigeonhole

---

Contributors_Page_Source/index.js

Standardize JS code to stick to StandardJS code style

---

C/Categorization.json
C/Classification.json
G/Grouping.json

Issue #481 
Description:
Add words Categorization, Classification, Grouping.

Add Categorization, Classification, Grouping

---

C/Cataloging.json
C/Class.json
C/Cluster.json
C/Codification.json
D/Divide.json
G/Grade.json
G/Group.json
S/Stratification.json
T/Taxonomy.json

The Pull Request resolves Issue #481
Description:
Words added: Stratification, Taxonomy, Class, Group, and Grade.

Words added: Stratification, Taxonomy, Class, Group, and Grade

---

S/Stoked.json

Stoked.json

---

L/Loquacious.json
M/Move_noun.json
M/Move_verb.json
M/Movement.json
S/Soporific_adjective.json
S/Soporific_noun.json

The Pull Request resolves Issue #273

Added words Movement,Move,Loquacious,Soporific 

---

U/Unerringly.json

Description:
Added Unerringly.json

Added Unerringly.json

---

M/Maim.json
M/Malingerer.json

Description:
Added Maim, Malingerer

Added M words Maim, Malingerer #407

---

T/Tour_noun.json
T/Tour_verb.json

The Pull Request resolves Issue
#121 
Description:
Adds definitions for the word `tour`

add tour definitions

---

K/Kite.json

Description:
Add Kite.json to repo

Add Kite.json

---

R/River.json

The Pull Request resolves Issue 
#25 
Description:
Adds definition of the word `river`

add river definition

---

A/Adjoin.json

Description
Added word 'Adjoin'

Added word 'Adjoin'

---

A/Adjoin.json
D/Derive.json

Description:
Added word 'Derive'

Added word 'Derive'

---

M/Mullock.json

add word Mullock
Description:
add word Mullock

add word Mullock

---

A/Ancillary.json

The Pull Request resolves Issue #[356]
Description:
Added Ancillary

Add Ancillary #356

---

C/Convoluted.json
P/Poultry.json

Description:
Added word "Convoluted"

Add Convoluted.json

---

M/Mellifluous.json

Add Melliffluous

---

G/Gator.json

Description:
Added definition of word gator under G/Gator.json

Added G/Gator.json

---

E/Envy.json

Add Envy.json to folder E

---

D/Drown.json

Description:
Added "Drown" as the new word to the dictionary.

Added word Drown to the list.

---

L/Lazy.json

creating lazy.json

---

P/Pollyannaish.json

Added Pollyannaish

---

B/Bastardization.json
P/Pollyannaish.json
S/Sardonic.json

Description:
A new word Bastardization added.

Added New Words :art:

---

.travis.py

show a link to a json linter

---

A/Abysmal.json

Added Abysmal :sparkles:

---

H/Harangue.json
H/Hoodwink.json
H/Huzzahs.json

Description:
Added words to H.

Added words to H :boom:

---

J/Jejune.json

Description:
Added word Jejune in J.

Added Jejune :beers:

---

F/Famous.json
I/Illustrious.json
I/Impeccable.json
V/Venerable.json

The Pull Request resolves Issue #543
Description:
Words added: Famous, Impeccable, Illustrious, and Venerable.

Words added: Famous, Impeccable, Illustrious, and Venerable.

---

.travis.py

did not test good enough before PR my bad

fix string template

---

C/Cheesy.json
C/Clumsy.json
C/Cutesy.json

The Pull Request resolves Issue #[547]
Description:
added words Cheesy, Clumsy, Cutesy.

added words ending in sy

---

M/Mocking.json

add word mocking
Description:
add word mocking

add word mocking

---

M/Mango.json
M/Mean.json
M/Mirror.json

Issue #407
Description:
Added 3 words to "M" section, they are: Mirror, Mango and Mean.

Added 3 words to M section.

---

B/Biopsy.json
W/Whimsy.json

The Pull Request resolves Issue #547

Add Biopsy and Whimsy

---

I/Intent.json

Added Intent.json

---

C/Controversy.json
C/Hypocrisy.json
C/Prophesy.json

The Pull Request contributes to Issue #547
Description:
Added Controversy, Hypocrisy, and Prophesy to the vocabulary.

Add Controversy, Hypocrisy, and Prophesy to the vocabulary.

---

B/Bibliopole.json
D/Deglutition.json
D/Deracinate.json
D/Douceur.json
S/Serendipity.json
S/Slapdash.json

Increased Vocabulary :alembic:

---

.travis.py
C/Controversy.json
H/Hypocrisy.json
P/Prophesy.json

The Pull Request contributes to Issue #547 #564
Description:
Add Controversy, Hypocrisy, and Prophesy to the vocabulary.

 Add test to catch files in the wrong folder 

---

I/Iceberg.json

The Pull Request resolves Issue #[535](https://github.com/Showndarya/Hacktoberfest/issues/353)
Description:
Add word iceberg
* The `#[535]` should be replaced with the specific Issue being referenced.

add word Iceberg

---

E/Eminent.json
P/Paramount.json
P/Preeminent.json
P/Prominent.json

The Pull Request resolves Issue #543
Description:
Words added: Eminent, Preeminent, Prominent and Paramount.

Words added: Eminent, Preeminent, Prominent and Paramount.

---

A/Arduous.json

Arduous added

---

D/Devil.json

Added "Devil" definition in D Folder.

Added Devil word on D Folder.

---

J/Junket.json
P/Passage.json
R/Ramble_noun.json
R/Ramble_verb.json
R/Ride.json
S/Sailing.json

Passage,Ramble,Ride,Sailing,Junket

---

L/Limpsy.json
Q/Quinsy.json
U/Unsonsy.json

The Pull Request resolves Issue #[547]
Description:
added Limpsy, Quinsy, Unsonsy

added Limpsy, Quinsy, Unsonsy

---

I/Ineluctable.json
I/ineluctable.json

Description:
I added the word "ineluctable".

Added by carlos

---

A/Autopsy_noun.json
A/Autopsy_verb.json
B/Busy_adjective.json
B/Busy_noun.json
B/Busy_verb.json

The Pull Request resolves Issue #547
Description:
adding 2 new words (Autopsy and Busy ).

adding 2 new words

---

M/Miracle.json

Description:
Added "miracle" word definition.

Added Miracle word definition

---

C/Creasy.json
D/Drowsy.json

The Pull Request resolves Issue #547 
Description:
Added Creasy and Drowsy words.

Add Creasy and Drowsy

---

N/Nature.json

Add ChathurangiJayawardana to Contributors list

---

S/Small.json

Add a Small word

---

Z/Zinger.json
Z/Zoology.json

Added new words starting with Z

---

S/Supercalifragilisticexpialidocious.json

Added supercalifragilisticexpialidocious

---

M/Maintain.json

Added Maintain

---

T/Tree.json
T/Trivium.json

Description:
"Trivium" word definition added.

Add trivium

---

M/Marriage.json
T/Tree.json
T/Trivium.json

Description:
Added Marriage word definition

Add marriage

---

L/Linux.json

Added L/Linux.json

---

.travis.py
.travis.yml
requirements.txt
schema.json

The Pull Request resolves Issue #584
Description:
- defined schema for the vocabulary file.
- Added the jsonschema validation to the travis-ci pipeline

added jsonschema validation to ci

---

H/Hallucination.json

Description:
word added: Hallucination

Add Hallucination

---

A/Autopsy.json
B/Busy.json
G/Gypsy.json

The Pull Request resolves Issue #547 
Description:
Add new words i.e., autopsy, busy and gypsy to vocabulary

Add autopsy, busy and gypsy to vocabulary

---

D/Demonetize.json
K/Kosher.json

Added D/Demonetize.json

---

D/Dean.json

The Pull Request resolves Issue  #57
Description:
Add "dean"

Add "dean"

---

C/Code.json

added code.json

---

H/Hibernate.json

The Pull Request resolves Issue #597
Description:
Added hibernate

Added hibernate as bears need it a lot

---

A/Amateur.json
A/Amazing.json
A/Analytical.json
A/Animate.json
A/Artificial.json
A/Assault.json

The Pull Request adds to Issue #52 
Description:
'A' words from Blackalicious' Alphabet Aerobics

Adds Alphabet Aerobics' A words

---

D/Dignified.json
E/Exemplary.json
H/Honourable.json
S/Solemn.json

The Pull Request resolves Issue #543
Description:
Dignified, Solemn, Exemplary, and Honourable.

Words added Dignified, Solemn, Exemplary, and Honourable.

---

Z/Zugzwang.json

added zugzwang

---

C/Courtesy.json

The Pull Request resolves Issue #547
Description:
Added courtesy definition

added courtesy definition

---

R/Retroperitonial.json

Added new word to R

---

H/Hew.json
H/Homeostasis.json

Description:
Added two words: Hew and Homeostasis

Adding Hew and Homeostasis

---

M/Mercury.json

I added a new word with the letter m, Mercury

Add Mercury

---

P/Puggle.json

The Pull Request works Issue #25 
Description:
Added word "Puggle"

Issue #25 - added word Puggle

---

H/Hail.json
H/Hand.json
H/Hardware.json

I just added the following words: Hail, Hand & Hardware.

Added the following words: Hail, Hand and Hardware

---

J/JavaBean.json
J/Joystick.json

The Pull Request resolves Issue #[62]
Description:
Added the definitions of Joystick and Javabean in JSON

adding Joystick and Javabean json files

---

H/Hostage.json
H/Humor_noun.json
H/Humor_verb.json

Description:
Added words `hostage` and `humor` noun and verb variants

add words hostage and humor noun and verb variants

---

R/Rover.json

Description:
Adds the word Rover, in accordance to the template

Added Rover.json

---

F/Fake_noun.json

Description:
* The #58 should be replaced with the specific Issue being referenced.

Add Fake noun

---

C/Continuation.json

Description:
Adding the word Continuation

Adding "Continuation" for issue #627

---

P/Powershell.json

The Pull Request  Add The defintion for PowerShell

Add - PowerShell.json

---

C/Cross.json
S/Syzygy.json

Syzygy.json

---

Z/Zap.json
Z/Zoo.json

{
"word": "Zoo",
"definitions": [
"an establishment which maintains a collection of wild animals, typically in a park or gardens, for study, conservation, or display to the public."
],
"parts-of-speech": "Noun"
}

add-the-word-"Zoo"

---

C/Cryptography.json

added cryptography.json

---

V/Vacuous.json

The Pull Request resolves Issue 
#638 
Description:
Add definitions for the word vacuous

add vacuous definitions

---

C/Caballine.json

Description:
Adds the adjective "caballine" with definition

Add caballine

---

Z/Zap.json
Z/Zigzags.json
Z/Zoo.json

{
"word": "Zigzags",
"definitions": [
"a line or course having abrupt alternate right and left turns."
],
"parts-of-speech": "Noun"
}

Add zigzags word

---

D/Damascene.json

Description:
Adds the adjective "Damascene" with definition

Add Damascene

---

Z/Zap.json
Z/Zigzags.json
Z/Zloty.json
Z/Zodiac.json
Z/Zoo.json

{
"word": "Zodiac",
"definitions": [
"An imaginary belt in the heavens, in the middle of which is the ecliptic, or sun's path. It comprises the twelve constellations, which one constituted, and from which were named, the twelve signs of the zodiac."
],
"parts-of-speech": "Noun"
}

Add zodiac word

---

K/Ketchup.json

added Ketchup.json

---

V/Vacillate.json
V/Vacuous.json
V/Vagary.json
V/Vagrant.json
V/Vainglorious.json

The Pull Request resolves Issue "Add words Vacillate, Vacuous, Vainglorious, Vagary and Vagrant"
Description:
Vacillate, Vacuous, Vainglorious, Vagary and Vagrant were added with definitions.

Added words Vacillate, Vacuous, Vainglorious, Vagary and Vagrant

---

C/Cacaphony.json
C/Camouflage.json
C/Cannibal.json

Description:
The words Cacaphony, Camouflage, Cannibal were added to the "C" Group.

Added Cacaphony, Camouflage, Cannibal

---

B/Book.json

The Pull Request
Description:
Add word Book

Add word Book

---

G/Golf.json

The Pull Request resolves Issue #59
Description:
Added the noun "Golf" to G Directory

add Golf.json to G directory

---

Z/Zone.json

Description:
Added the word Zone.

Added Zone

---

C/Claustrophobia.json
C/claustrophobia.json

Description:
Added claustrophobia.

Added claustrophobia

---

H/Holocaust.json
H/Holster.json
H/Homage.json
H/Homely.json

The Pull Request resolves Issue #[597]
Description:
Added 4 words: Holocaust, Holster, Homage, Homely

Added 4 words: Holocaust, Holster, Homage, Homely

---

B/Beard.json

added Beard.json

---

S/Sheath.json
S/Sophomore.json
T/Thrice.json

Added three uncommon words

---

C/Communism.json

Description:
Added the word Communism to the C folder

Added the word communism

---

N/Nil_adjective.json
N/Nil_noun.json

The Pull Request resolves Issue #107 
Description:
Add new word = 'Nil'

Add new word 'nil'

---

L/Lucid.json
L/Luddite.json
V/Vulgarian.json

Added New Definitions to Python Chart

---

F/Feelings.json
L/Loop.json

Added FeelingS

---

A/Anthropology.json

This patch is part of #691
The Pull Request (partially) resolves Issue #691
Description:
Addition of `Anthropology`, its definition and its parts of speech.

Anthropology

---

B/Beer.json

Description:
Added word "Beer"

Add word Beer

---

V/Volcanology.json

The Pull Request resolves Issue #691
Description:
Added Volcanology

add Volcanology

---

W/Worldly.json

add 'Worldly'

---

U/Uranology.json

Description:
add word Uranology

add Uranology

---

R/Rheumatology.json
V/Victimology.json

Description:
added Victimology

add Victimology

---

B/Biology.json
C/Criminology.json
D/Dermatology.json

The Pull Request resolves Issue #691

add 'Biology', 'Criminology', and 'Dermatology'

---

K/Kind.json

My PR to add the "Kind" work to this repository ! #hacktoberfest

Add Kind in the K directory

---

A/Apartheid.json

The Pull Request adds Apartheid to the dictionary.

Words added to the JSON dictionary

---

W/Wiggle_noun.json
W/Wiggle_verb.json
W/Willful.json
W/Willowy.json
W/Wrangle_noun.json
W/Wrangle_verb.json
W/Wrath.json
W/Wreak.json

The Pull Request resolves Issue #693 , #696

add 6 words to W

---

G/Guilty.json
G/Guitar.json
W/Woeful.json

2 new words

---

W/Wonk.json

Description:
Adding the word Wonk

adding Wonk - #699

---

W/Woe_interjection.json
W/Woe_noun.json

Description:
Adding the word Woe

Adding Woe

---

W/Woozy.json

Description:
Adding the word Woozy

adding Woozy - #699

---

C/Cover.json

#627 Adding cover.json

---

E/Ecology.json
E/Epistemology.json
O/Oncology.json
P/Pharmacology.json

Description:
add the words
- ecology
- epistemology
- oncology
- pharmacology

My additions

---

W/Withdrawn.json
W/Wither.json
W/Withhold.json
W/Withstand.json

The Pull Request resolves Issue #696

added withdrawn, wither, withhold, withstand

---

W/Womenfolk.json
W/Woody.json

Description:
Adding Womenfolk and Woody

Add Womenfolk and Woody

---

C/Capacity.json

Description:
Adding Capacity.Json

#627 Adding Capacity.Json

---

C/Wherry.json
M/Map.json
W/Wheeple.json
W/Whereabout.json
W/Wherry.json

Description:
#627 Adding Congruent.json

#627 Adding Congruent.json

---

W/Wold.json
W/Wolfberry.json

The Pull Request resolves Issue #699 
Description:
Added the words Wolfberry and Wold

added Wold and Wolfberry

---

W/Wheel.json
W/Wheelie.json
W/Wrathy.json
W/Wreak.json

Adding Wrathy

---

W/Winnow.json

Winnow Definition

---

W/Woman.json
W/Womb.json
W/Wonderful.json

The Pull Request resolves Issue #699 
Description:
Added Woman, Womb, Wonderful

Added Woman, Womb, Wonderful for GitHub #699

---

C/Corpse.json

Description:
Added word corpse, a noun.

Added word Corpse

---

W/Whiff.json
W/Whine.json

Second try after rebasing fail
Resolves #695 
Add words: 
* Whiff
* Whine

Add words Whiff and Whine

---

D/Defenestration.json

Description:
I added the word Defenestration

Added Defenestration

---

S/Superluminal.json

Description:
Astronomy. appearing to travel faster than the speed of light.

Added: Superluminal

---

W/Workaholic.json
W/Workbook.json
W/Workshop.json

The Pull Request resolves Issue #699 
Description:
Added Workaholic.json, Workbook.json, Workshop.json

Issue #699 - 

---

Z/Zest.json
Z/Zest.json~

Description: creates Zest.json

added Zest to Z words

---

C/Champion

Add word Champion

---

Z/Zawn.json
Z/Zoographer.json

The Pull Request resolves Issue #[741] and #[742]
Description:
Added a few new words

Added a few "Z' words

---

W/Wretch.json

Add Wretch

---

W/Wilt_noun.json
W/Wilt_verb.json
W/Wince.json
W/Wisp.json

Added words:
- Wilt (noun and verb)
- Wince
- Wisp

Added words Wilt, Wince and Wisp

---

W/Wrinkle_noun.json

Add Wrinkle (noun)

---

README.md

The Pull Request resolves Issue #767 
Description:
Change REAMDME.md

FixBrokenLink

---

P/Prowess.json
V/Vacuous.json

The Pull Request resolves Issue 
#25 
Description:
Adds definitions for the word `Prowess`

Add prowess json

---

T/Terminology.json
T/Tetralogy.json
T/Thanatology.json
T/Timbrology.json
T/Trichology.json
T/Trilogy.json

I added six words: trilogy, terminology, thanatology, timbrology, trichology and tetralogy.
(the timbrology is found in the British dictionary.)

Added trilogy, terminology, thanatology, timbrology, trichology and tetralogy

---

E/Epidemiology.json
H/Hydrobiology.json
L/Laryngology.json
O/Oceanology.json

The Pull Request resolves Issue #691
Description:
added Epidemiology, Hydrobiology, Laryngology, Oceanology

added words Epidemiology, Hydrobiology, Laryngology, Oceanology

---

W/Wrench_noun.json
W/Wrench_verb.json

Description:
Add Wrench noun and verb

Add Wrench

---

W/Wrester.json

The Pull Request resolves Issue #693 
Description:
Add Wrester word

Add Wrester

---

C/Cattle.json

Description:
Add the noun "Cattle" to the directory C

add noun Cattle

---

W/Writ.json
W/Wroth.json
W/Wrung.json

The Pull Request for issue #693 
I added three words - writ, wrung and wroth.

Add words starting with 'wr'
