Showndarya/Hacktoberfest

- E/Ecclesiology.json
- G/Gemology.json
- G/Gynaecology.json
- H/Heterodox.json
- H/Heterogeneous.json
- H/Hummus.json
- H/Humus.json
- M/Microbiology.json
- P/Parasitology.json
> add 9 words

- D/Discommode.json
- F/Fortuitous.json
Description:
Added word discommode
> Added Discommode.json

- H/Horrendous.json
Description:
added the word Horrendous
> added Horrendous

- C/Cognitive.json
- M/Migration.json
- M/Minimalist.json
- S/Succinct.json
- U/Upgrade.json
> Add Succinct

- Y/Youthquake.json
The Pull Request resolves Issue #51 
Description:
Added the term `Youthquake`.
> Added Youthquake

- C/Car.json
Description:
Add the Car word in C folder
> Add car word

- W/Wary.json
Description:
Adds the definition for 'wary'
> Add definition for wary

- B/Backpack_verb.json
The Pull Request resolves Issue #273
Description:
Adds the verb definition of 'backpack'
> Add 'backpack' verb definition.

- C/Cabin.json
> Cabin.json

- W/Wolf_noun.json
- W/Wolf_verb.json
- W/Wonderer.json
- W/Wood.json
- W/Workbench.json
- W/World.json
Description:
Added 5 words (6 considering wolf as name and verb)
World
Workbench
Wood
Wolf
Wonderer
> Added: 5 new words starting with Wo

- W/Wistful.json
- W/Witless.json
- W/Witticism.json
- W/Wizardry.json
- W/Wizened.json
> Added words wistful, witless, witticism, wizardry and wizened

- W/Workless.json
- W/Workroom.json
- W/Workstation.json
- W/Worktop.json
- W/Workweek.json
I added 5 words starting with wo:
- Workless
- Workroom
- Worktop
- Workstation
- Workweek
> Added 5 words starting with wo

- Q/Qwerty.json
Description:
Added Qwerty.json
> Added Qwerty.json

- Y/Yahoo.json
- Y/Yard.json
- Y/Yeah.json
- Y/Yeoman.json
- Y/Yet.json
- Y/Yield.json
- Y/Yoke.json
- Y/Yosemite.json
- Y/Young.json
- scripts/generate_words.py
The Pull Request resolves Issue #51
Description:
- Added helper script which generates JSON files given the starting letter/s of a word
- Added words starting from Y.
PS: Its a simple script to get started and there is obviously scope for adding more functionality and  improvements.
> Words and helpers

- B/Backdate.json
The Pull Request resolves Issue #807
Description:
Added backdate
>  added backdate

- J/Jaywalk.json
- J/Jejunum.json
- J/Jiffy.json
- J/Jujitsu.json
> Added some words starting with J

- P/Prevaricate.json
- P/prevaricate.json
> added prevaricate definition

- O/Obliviate.json
The Pull Request resolves Issue #807
Description:
Adds Obliviate
> Add Obliviate.json

- C/Cyberpunk.json
The Pull Request resolves Issue: #627 
Description:
Add Cyberpunk
> Add Cyberpunk #627

- C/Cynicism.json
The Pull Request resolves Issue #831
> Capitilize parts of speech for Cynicism #831

- A/Anticipate.json
I have added a word  ending with `ate` in  A folder of your Project. 
#807
> added a word ending with ate in A folder

- L/Liquidate.json
- M/Mutilate.json
The Pull Request resolves Issue #[807]
Description:
Add Liquidate and mutilate
> add liquidate and mutilate

- A/Adventure.json
adding adventure.json to the list
> Word Adventure added

- A/Animal.json
> added Animal

- T/Truncate.json
The Pull Request resolves Issue #[807]
Description:
added "Truncate"
> Add -ate words (Issue #807)

- P/Paludal.json
The Pull Request resolves issue #25 
Description:
Added word "Paludal"
> Added word "Paludal"

- A/Abate.json
> Created Abate.json

- C/Cardiology.json
- C/Chronology.json
- D/Derive.json
The Pull Request contributes to Issue #691
Description:
Added word 'Chronology'
Added word 'Cardiology'
Removed broken version of Derive (Will add back in a seperate PR)
> added chronology

- M/Malefic.json
- M/Mammock.json
Description:
Added two words that starts with M - Malefic and Mammock
> Added Malefic and Mammock

- A/Appetite.json
- O/Odyssey.json
Description:
the word Odyssey is added along with Appetite
> Added new words 'Appetite' and 'Odyssey'

- C/Cytology.json
Description:
Added word Cytology
- Noun
- The branch of biology that deals with the formation, structure, and function of cells.
> Added Cytology

- A/Apraxia
> Add Apraxia

- B/Baccalaureate.json
- R/Retaliate.json
The Pull Request resolves Issue #807 
Description:
Added files for words "Baccalaureate" and "Retaliate".
> Added Baccalaureate and Retaliate

- E/Entropy.json
Added a word to the E category.
Description:
Added the word Entropy, its definition, meaning and part of speech.
> Added a word starting with E

- D/Deep.json
Description:
Added a new word - Deep.
> Adding word Deep

- E/Electron.json
> Added electron.js

- T/Towel.json
Added the definition of the word "towel", as it is in the Hitchhiker's Guide to the Galaxy
> Pull request

- P/Powershell.json
- W/Windows.json
> Add Windows

- G/Guttersnipe.json
> Added guttersnipe

- I/Incredible
> Revert "Create Incredible"

- M/Music.json
> Added Music

- B/Bromide.json
Description:
Added word Bromide
> Adds Bromide

- G/Glossy.json
- I/Invade.json
Description:
Addition of new word.
> New Word Included

- A/Alacrity.json
Description:
Added Alacrity.json
> Added Alacrity.json

- A/Abdicate.json
- A/Abhor.json
- A/Abhorrent.json
- A/Abide.json
- A/Ablaze.json
Description:
Added Abdicate.json, Abhorrent.json, Abhor.json, Ablaze.json and Abide.json
> Added Abdicate.json, Abhorrent.json, Abhor.json, Ablaze.json, Abide.json

- C/Cogitate.json
- C/Commensurate.json
- C/Commentate.json
- C/Conglomerate_Adjective.json
- C/Conglomerate_Noun.json
- C/Conglomerate_Verb.json
- D/Degenerate_Adjective.json
- D/Degenerate_Noun.json
- D/Degenerate_Verb.json
- E/Equate.json
- E/Equivocate.json
- E/Extrapolate.json
- F/Fabricate.json
The Pull Request resolves Issue #807 
Description:
added files for the words:
- Conglomerate
- Commensurate
- Cogitate
- Commentate
- Degenerate
- Extrapolate
- Equate
- Equivocate
- Fabricate
> add -ate words

- B/Bachelor.json
- B/Backbone.json
- B/Bait.json
- B/Bestir.json
- B/Bevy.json
Description:
Added Bachelor.json, Bait.json, Backbone.json, Bestir.json and Bevy.json
> Added Bachelor.json, Bait.json, Backbone.json, Bestir.json, Bevy.json

- C/Computer.json
> Added Computer

- D/Disdain.json
The Pull Request resolves Issue #884
Description:
added Disdain.json
> added Disdain

- F/Fiction.json
> Added Fiction

- D/Digit.json
This Pull Request is for Issue #884.
The Pull Request is to add the Digit.json file into the D folder for Hacktoberfest 2018.
Description: The file contains the word, its definition, and its part of speech.
> Add Digit.json into D folder for Hacktoberfest 2018

- P/Petrochemistry.json
This PR will add a new word to the list `Petrochemistry`
> Add new word Petrochemistry

- M/Multiarticulate
The Pull Request resolves Issue #807 
Description:
Added Multiarticulate
> Added 'Multiarticulate'

- .vs/ProjectSettings.json
- D/Diligent.json
The Pull Request resolves Issue #[884]
Description:
Added 'diligentl
> Added 'diligent'

- W/Workaround.json
The Pull Request resolves Issue #699 
Description:
Added the word Workaround to the W directory
> added Workaround.json

- D/Diatribe.json
- D/Disparate.json
Closes https://github.com/Showndarya/Hacktoberfest/issues/884
Description:
> Added Disparate

- P/Postern.json
Description:
Added postern to P folder as a contribution for the Hacktoberfest.
> Added postern to P

- E/Excelsior.json
> add excelsior

- D/Disgruntled.json
Closes https://github.com/Showndarya/Hacktoberfest/issues/884
Description:
> Added Disgruntled

- D/Device.json
- L/Laptop.json
The Pull Request resolves Issue #[57]
Description:
Device: a thing made or adapted for a particular purpose.
> add word device

- D/Disparage.json
Closes https://github.com/Showndarya/Hacktoberfest/issues/884
Description:
> Added Disparage

- D/Dilettante.json
Closes https://github.com/Showndarya/Hacktoberfest/issus/884
Description:
> Added Dilettante

- G/GGWP
> Revert "Create GGWP"

- M/Methodology.json
Description:
Added Methodology.json
> Added Methodology.json

- A/Auxiliary.json
> Added new word : Auxiliary

- B/Biosurgery.json
- C/Consult.json
The Pull Request resolves Issue #[356]
Description:
* The `#[356]` should be replaced with the specific Issue being referenced.
> Added Biosurgery Word ending with 'ry'

- A/Averruncate.json
> Added word "Averruncate"

- D/Deflate.json
- D/Desecrate.json
- S/Satiate.json
- U/Understate.json
- U/Undulate.json
The Pull Request resolves Issue #807
Description:
Added 'Deflate', 'Desecrate', 'Satiate', 'Understate' and 'Undulate'.
> Added 'Deflate', 'Desecrate', 'Satiate', 'Understate', 'Undulate'

- A/Accessory_adjective.json
- A/Accessory_noun.json
- A/Adultery.json
- A/Allegory.json
- A/Ancestry.json
- A/Apery.json
- A/Apothecary.json
- A/Archery.json
- A/Armoury.json
- A/Artery.json
- A/Articulatory.json
- A/Artillery.json
- A/Asymmetry.json
- A/Audiometry.json
- A/Auditory.json
- A/Auxiliary_adjective.json
- A/Auxiliary_noun.json
Description:
In response to Issue #356 added Accessory as a noun and adjective and Adultery and many more.
> Added Words ending with 'ry' and starting with 'a'

- S/Stuff.json
Description:
Added definitions for "Stuff".
> added Stuff

- J/Juggernaut.json
Description:
Added a file for "Juggernaut".
> add Juggernaut.json

- M/Military_adjective.json
Description:
Add "Military", adjective
> added Military adjective

- T/Trivial.json
> Added word Trivial

- Z/Zelda.json
> added Zelda

- Z/Zebra.json
> added zebra

- Z/Zealotry.json
> added zealotry

- Z/Zealous.json
> added Zealous.json

- D/Disheveled.json
- D/Dispersed.json
The Pull Request resolves Issue #884 
Description:
Added definitions for Disheveled and Dispersed
> adding Disheveld and Dispersed

- S/Shallow.json
> Add adjective 'Shallow'

- S/Shortcut.json
> added word shortcut

- D/Discern.json
> Added Discern.json

- D/Determination.json
> Adding a new word "Determination" in json format

- O/Orbit_noun.json
- O/Orbit_verb.json
- S/Soccer.json
> Add O/Orbit

- A/Abroad.json
> added Abroad word

- O/Often.json
> add often word

- D/Dynamite
> added Dynamite

- S/Sociology.json
> add sociology

- S/Summary.json
> add summary

- A/Apiculture.json
Description:
Adds new file for word- Apiculture (noun)
> Adds new word- Apiculture

- E/Exodus.json
> Added Exodus.json to E

- V/Vegetarian.json
> Added word Vegetarian

- P/Phoenix.json.txt
The Pull Request resolves Issue addition of new word
Description:
Added a new word to this exquisite collection :)
P.S Thank you
> Added new word Phoenix

- P/Paparazzo.json
> added new word

- C/Caster.json
- C/Council.json
- H/Horizontal.json
- S/Seer.json
Caster
Council
Horizontal
Seer
> add four vocabulary

- C/Crapulous.json
Description:
Added word 'crapulous'
> Added Crapulous.json

- T/Take.json
> added Take.json

- T/Tactful.json
> added word Tactful

- T/Tank.json
> Added Tank.json

- T/Taste.json
> Added Taste.json

- T/Tax.json
> added Tax.json

- A/Askhole.json
> Added askhole

- Y/Yank.json
> added word yank

- B/Beach.json
- I/Idiot.json
> Add Beach.json

- F/Fluctuate_verb.json
- F/fluctuate_verb.json
Description:
Added a new word -> "Fluctuate"
> Added the word - fluctuate

- C/Clinic.json
Description:
Added the word clinic
> added the word Clinic

- H/Hippopotomonstrosesquipedaliophobia.json
> Added Hippopotomonstrosesquipedaliophobia

- C/Clergy.json
Description:
added the word clergy
> added the word clergy

- H/Hate.json
- L/Love.json
- S/Sorry.json
Description:
Added the word Hate
> Added Hate

- S/Spoilt.json
> Added Spoilt

- O/Obtuse.json
Sample pull request:
Added:
{
"word": "Obtuse",
"definitions": [
"annoyingly insensitive or slow to understand.",
"(of an angle) more than 90° and less than 180°"
],
"parts-of-speech": "Adjective"
}
> Added Obtuse to the Directory

- M/Monkey.json
Description:
Add word 'Monkey'
> add monkey

- B/Brightwork.json
Description:
Added Word Brightwork
> Added Word Brightwork

- P/Proliferation.json
Description:
I added `Proliferation` to the P words. 😸
> Proliferation word added

- S/Superfluous.json
Description:
Add a new word under S: Superfluous
Notes:
> Add definition to S/Superfluous

- F/Fragor.json
- J/Jumboism.json
> Ijobera patch 2

- C/Credit_noun.json
> Added word Credit_noun.json

- C/Corybantic.json
- F/Fragor.json
- J/Jumboism.json
> Ijobera patch 3

- I/Idiologism.json
- S/Statoscope.json
> J repil patch 2

- A/Astonish.json
> added Astonish.json

- L/Lunatic.json
> added lunatic

- E/Exhausted.json
> added exhausted

- R/Rarry.json
> Add word rarry

- X/Xerxes.json
> Add word xerxes

- C/Concise.json
- S/Scout.json
> Concise word added

- Q/Quizmaster.json
> added quizmaster

- Y/Yin-yang.json
> Added Yin-yang

- T/Tenant.json
> Added tenant word.

- R/Rubble.json
- T/Tergiversation.json
Description:
Added the word tergiversation to the T Directory
> Created: tergiversation.json

- A/Anesthesiologist.json
The Pull Request adds in section A.
Description:
Added Json for the word Anethesiologist
> Created Anesthesiologist.json

- I/Iridescent.json
The Pull Request resolves Issue #353 
Description:
Added definition of word "Iridescent".
> Added definition of Iridescent.

- P/Plethora - Copy.json
- P/Pluviophile.json
> Added word Pluviophile

- P/Pivot.json
> Added word Pivot

- D/Diminutive_Adjective.json
- D/Diminutive_Noun.json
I added entries for "Diminutive", both noun and adjective.
This PR fixes #884
> Adding Diminutive (Adjective and Noun) fix #884

- A/Agoraphobia.json
Description:
Added Agoraphobia
> Added Agoraphobia

- A/Apply.json
> Added word apply

- C/Catch.json
Description:
Added the word catch
> Added Catch

- D/Diversity.json
The Pull Request resolves Issue #[884]
> Update and rename Dictionary.json to Diversity.json

- C/Caculate.json
> add caculate.json

- E/Enthusiastic.json
> Added "Enthusiastic" because of my enthusiasm

- A/Atom.json
Description:
Add Atom noun in A folder.
> add Atom noun in A

- H/Honest.json
> Added new word 'Honest'!

- Y/Yesteryear.json
> add yesteryear

- D/Dissent.json
- D/Divulge.json
The Pull Request resolves Issue #884
Added Divulge and Dissent. It failed test last time due to lack of capitalization.
> added Divulge Dissent

- H/Hacktoberfest.json
> Added Hacktoberfest

- H/Hoax.json
- I/Intricate.json
> Added "Intricate"

- S/Super.json
> add super word

- .github/ISSUE_TEMPLATE/add-word---word---and-words-related-to---word--.md
- .github/ISSUE_TEMPLATE/add-word---word--.md
- .github/ISSUE_TEMPLATE/custom.md
The Pull Request resolves Issue #1206
Description:
I've made changes to address the problems outlined in issue #1206
> Fix issue templates

- A/Ant.json
- S/SriLanka.json
> created the Ant.json

- A/Aquatic.json
> Adding Aquatic.json

- A/Auspicious.json
- N/Nice.json
- N/Nigga.json
> Added the word Auspicious

- A/Alligator.json
> Added Alligator

- P/Pentagon.json
The Pull Request resolves Issue #1159
Description:
Add pentagon word
> add pentagon

- A/Agastopia.json
Description:
Added word: "Agastopia"
> Agastopia word

- N/Napalm.json
> Add napalm

- H/Harrowing.json
- O/Opulence.json
- P/Paradigm.json
> Added Opulence.json

- C/Contemplative.json
Description:
Add definition for "contemplative" in `Contemplative.json`
> Add definition for "contemplative"

- F/Fund.json
- H/High.json
> add Fund.json

- A/Alchemist.json
- abstentious.json
> add abstentious.json

- A/Abase.json
> Created Abase.json in [A/Abase.json]

- S/Synergy.json
Description:
Added a new file Synergy.json
> added Synergy file

- M/Meatball.json
Description:
Added Meatball to the list.
> Added Meatball

- C/Curfew.json
> Added a word - "Curfew"

- B/Bonjwa.json
- H/Hikikomori.json
Description:
Added "Bonjwa" and "Hikikomori" to the list.
> add Bonjwa and Hikikomori

- N/Neocracy.json
> Added Neocracy

- E/Egregious.json
The Pull Request resolves Issue #1268
Added the word 'Egregious'.
> Added Egregious - Egregious.json

- A/Atheroma.json
add 'Atheroma' word into folder 'A'
> add Atheroma.json

- I/Iconic.json
- I/Iconium.json
- I/Iconize.json
- I/Iconoclast.json
- I/Iconomachist.json
- I/Ignitors.json
- I/Ignorant.json
- I/Isagoge.json
- I/Isagogics.json
- I/Isba.json
- I/Ischemia.json
- I/Isentropic.json
- I/Itch.json
- I/Itchings.json
- I/Itemizer.json
- I/Items.json
- I/Iterate.json
- I/Iteroparous.json
- I/Ithunn.json
- I/Ivories.json
- N/Nab.json
- N/Nap.json
- N/Net.json
- N/Nibble.json
- N/Nova.json
> Add 5 words

- A/Apple-knocker.json
> add apple-knocker

- X/Xylem.json
Addition of a new word **Xylem** under the letter **X**.
> Defining Xylem

- O/Ogdoad.json
> add noun Ogdoad

- E/Ethereal
Add Ethereal and its definition
> Add Ethereal to the list

- B/Bread.json
> Created Bread.json

- C/Courage.json
Description:
Courage is my favorite word from my school days. 
It gives me the strength all the time I hear it.
> Adding my favorite word Courage

- R/Robust.json
- R/Rose.json
> added Rose, Robust

- D/Dance.json
> Added word dance

- A/Autism.json
> Added Autism

- F/Funny.json
i have added "funny" for presentation purposes.
> added funny

- A/Angle.JSON
- W/Whisker.JSON
Description:
Added word whisker
> Added word Whisker

- H/Harmony.json
> added the word Harmony

- L/Linguistic_Adjective.json
Added New Word
Description:
Added New Word "Linguistic"
> New Word - Linguistic

- P/Pristine.json
The Pull Request resolves Issue ##1159
Description:
Added the word Pristine for the words starting with P.
> Added word P/Pristine

- E/Energy.json.txt
- M/Mercy.json.txt
> added Mercy word

- P/Profane.json
The Pull Request resolves Issue #1326
Description:
Added word Profane to the folder P
> Added Word Profane

- H/Heydey.json
The Pull Request resolves Issue #597
Description:
adding the word Heydey
> Adding Heydey

- C/Cryonaut.json
> Cryonaut definition

- G/Guru.json
The Pull Request resolves Issue #1373
Description:
Added the word "Guru" and its definitions.
> Added Word Guru

- X/Xylophilous.json
- X/xylophilous
> added xylophilous

- P/Pseudomania.json
- P/pseudomania
> add pseudomania

- F/Frustration.json
The Pull Request resolves Issue #58
Description:
Add the word "Frustration"
> Add Frustration

- D/Deep-seated.json
- D/Deep_seated.json
- H/Hostility.json
Added the word 'Deep-seated' #885
> Added Deep-seated

- C/Chubbiness.json
> add chubbiness

- P/Pillow.json
> Added Pillow.json file

- B/Breathtaking.json
- M/Malice.json
Add new words Breathtaking and Malice.
> Breathtaking and Malice

- P/Pragmatic.json
The Pull Request resolves Issue #[1397]
Description:
* The `#[1397]` should be replaced with the specific Issue being referenced.
> Renamed pragmatic.json to Pragmatic.json

- P/Prolific.json
The Pull Request resolves Issue #[1397]
> Updated and renamed prolific.json to Prolific.json

- E/Elf.json
- W/Walk_verb.json
> Adding entry for Elf

- I/Introvert.json
The Pull Request resolves Issue #353   
Description:
Added a new word: Introvert
> Introvert word added

- scripts/renamer.py
The Pull Request resolves Issue #1397 
Description:
> script for capitalizing json files

- Q/Quick.json
- Q/Quindim.json
The Pull Request resolves Issue  #72
Description:
Adding a Q words, and one of them could be a candidate for Android Q
> Adding Q Words

- V/Vizard.json
> Add Vizard

- A/Antecedent_noun.json
Description:
Create JSON file to contain word `Antecedent (noun)`
> Add Antecedent (noun)

- G/Gobbledygook.json
The Pull Request resolves Issue #1456 
Description:
added word Gobbledygook.
> G: added word "Gobbledygook"

- P/Palindrome.json
- S/Sea.json
> Palindrome

- O/Ostracize.json
> Hacktober | O - Ostracize

- C/Channel.json
- C/Chanterelle.json
The Pull Request resolves Issue 627
Description:
Added the words "Channel" and "Chanterelle" in C folder
> Added C words: Channel and Chanterelle

- L/Lockjaw.json
- X/Xerox.json
Description:
Added word Xerox in X folder
> added Xerox word in X folder, added Lockjaw word in L folder

- E/Extrovert_adjective.json
- E/Extrovert_noun.json
- P/Penumbra.json
- P/Peripatetic_adjective.json
- P/Peripatetic_noun.json
This pull request adds the word 'Penumbra' to the 'P' catalog of your database.
> Adding 'Penumbra' to the 'P' Folder

- C/Conquer.json
- E/Extrovert_adjective.json
- E/Extrovert_noun.json
- P/Peripatetic_adjective.json
- P/Peripatetic_noun.json
This pull request adds the word 'Conquer' to the 'C' folder in your database.
> Adding 'Conquer' to the 'C' folder

- E/Extrovert_adjective.json
- E/Extrovert_noun.json
- M/Meticulous.json
- P/Peripatetic_adjective.json
- P/Peripatetic_noun.json
This pull request adds the word 'Meticulous' to the 'M' folder in your database.
> Adding 'Meticulous' to the 'M' Folder

- K/Kinetic.json
Description:
Added the word kinetic having meaning in different areas
> Adjective :Kinetic added

- P/Paraphrase.json
The Pull Request resolves Issue #1159
Description:
Added the word paraphrase
(Paraphrase.json file added under the folder P)
> Added paraphrase

- G/Gabble.json
The Pull Request resolves Issue #59
Description:
* The #59 should be replaced with the specific Issue being referenced.
> added word Gabble

- P/Photograph.json
> added word

- P/Predict.json
This commit adds a new word "Predict".
> Added Predict

- P/Procrastinate.json
> Add new word: Procrastinate

- I/Polite.json
- P/Polite.json
- P/Predict.json
This commit adds a new word "Polite".
> Added Polite

- C/Creative.json
This commit adds the word Creative
> Added Creative

- N/Nun.json
Adds a description of the word Nun
> Add Nun.json

- M/Monetary.json
I've added a new word "Monetary".
> Added Monetary

- M/Modify
- M/Modify.json
Add a definition of modify to the m folder
Description:
I’ve added the word modify and it’s definiton to the m folder
> Add modify to the m folder

- M/Motivation.json
> New word is motivation

- B/Botany.json
- B/Bourdon.json
- O/Ominous.json
- O/Omit.json
The Pull Request for adding new words
Description:
Botany and Bourdon , 2 words of the BO family have been added
> Bourdon and Botany added

- P/Presume.json
- P/Produce.json
> Added Presume and Produce

- S/Schadenfreude.json
- W/Warbird.json
Description:
I added the word 'warbird', along with it's definition to the 'W' file.
> Add warbird, word and definition to W file.

- H/Handsome.json
> Add Handsome word

- A/Abashed.json
> add abashed

- E/Ebullient.json
> add ebullient

- V/Vessel.json
> Vessel.json

- P/Pertinent.json
> Add Pertinent

- P/Pivotal.json
- P/Pliable.json
- P/Plucky.json
Add adjective pivotal, pliable, and plucky
> Add plucky

- V/Velociraptor.json
Description:
added word 'Velociraptor'.
> added Velociraptor

- P/Premonition.json
> Add Premonition.json

- C/Chair.json
> Added word Chair

- B/Brawl_noun.json
- B/Brawl_verb.json
Description:
The noun and verb forms of the word "brawl" were added.
> Added Brawl noun and verb forms

- C/Catawampus.json
> Added catawampus to the list

- E/Epiphany.json
Description:
Epiphany(noun) added
> Epiphany(n) added

- Y/Yam.json
- Y/Yew.json
The Pull Request resolves Issue #51
> Added Yam and Yew #51

- P/Pizzazz.json
> Added Pizzazz to the list of words starting with P

- A/Amorphous_Adjective.json
Description:
Add `Amorphous` to the words
> PR: Add Amorphous

- B/Becharm_verb.json
The Pull Request resolves Issue #[25]
Description:
Added a Hacktober themed definition for 'Becharmed'.
>  'Becharm' definition.

- H/Haiku.json
- P/Peasant.json
- P/Pedantic.json
- R/Refrigerator.json
> Refrigerator

- P/Peasant.json
- P/Pedantic.json
> pc: adding P/Pedantic

- P/Phonetic_adjective.json
Description:
Added word - phonetic.
> created Phonetic_adjective

- Z/Zincic.json
Description:
Zincic.json added.
> added zincic.json

- F/Fluff_noun.json
- F/Fluff_verb.json
Added JSON files with the word "Fluff" and it's definitions. One file is a noun and the other is a verb.
> Added the json files for Fluff noun/verb.

- N/Neonate.json
> Added the word Neonate.

- M/Moonstruck_adjective.json
> Adding Moonstruck to M list

- A/Abatis_noun.json
> Added Abatis word.

- P/Pathogen_noun.json
- P/Pauper_noun.json
- P/Pavis_noun.json
The Pull Request resolves Issue #[1159]
Description:
Added pathogen, pauper, pavis.
> Added pathogen, pauper, pavis

- W/Worrit_noun.json
- W/Worrit_verb.json
The Pull Request resolves Issue #[699]
Description:
added worrit noun and verb
https://www.google.co.in/search?q=worrit&rlz=1C1GGRV_enIN750IN750&oq=worrit&aqs=chrome..69i57.393j0j4&sourceid=chrome&ie=UTF-8
> added worrit noun and verb

- W/Wreathen_adjective.json
The Pull Request resolves Issue #[693]
Description:
Added wreathen adjective
> Added wreathen adjective

- G/Glamping_noun.json
The Pull Request resolves Issue -
Description:
Created new file for new word
> Create Glamping_noun file

- Z/Zyme_noun.json
> Adding of Zyme word

- T/Tenon_noun.json
> Added tenon

- S/Sect_noun.json
Adding the word Sect to the dictionary as a noun.
> add sect noun to dictionary

- S/Seargent_noun.json
The Pull Request resolves Issue #[25]
[Issue_25](https://github.com/Showndarya/Hacktoberfest/issues/25)
- Added Seargent word
> Add Seargent noun

- O/Otorhinolaryngologist_noun.jason
Otorhinolaryngologist - one of the most complex words in english to pronounce
Description:
> One complex word in english

- B/Butter.json
> add Butter

- P/Pelvis_noun.json
> Added "Pelvis" #1159

- B/Berkelium.json
- B/Bromine.json
- D/Darmstadtium.json
- D/Dubnium.json
- I/Iridium.json
- L/Lawrencium.json
- L/Lead.json
- L/Livermorium.json
- N/Neptunium.json
- P/Promethium.json
- T/Tantalum.json
Description:
Added 5 chemical elements.
Happy Hacktoberfest
> Created five new "elements"

- P/Plural_adjective.json
Description:
Added the word "plural"
> add-plural

- P/Penultimate.json
- P/Preantepenultimate.json
Description:
Fourth to last in a series
> Add Preantepenultimate

- P/Penultimate.json
- P/Preantepenultimate.json
Description:
Add Penultimate to the P directory.
> Add Penultimate

- E/Elven_adjective.json
- H/Humbug.json
- V/Vulcan.json
- Y/Yankee.json
> Adding elven

- H/Humbug.json
- V/Vulcan.json
- Y/Yankee.json
> Adding three words

- G/Gazar_noun.json
- H/Humbug.json
- V/Vulcan.json
- Y/Yankee.json
> Addin gazar

- P/Punitive.json
- P/Putrid.json
> added 2 words #1159

- B/Bacano.json
Description:
* Add the `Bacano` word. 
> Add the word Bacano

- H/Handsome_adjective.json
The pull request expands the definition of handsome "things" with a more sophisticated definition.
https://www.dictionary.com/browse/handsome?s=t
> Updated handsome "things"

- P/Payload_noun.json
Description:
Added word Payload
Description:
Added word payload
> Added word Payload

- P/Primeval_adjective.json
Description:
Added the word primeval
> Added word primeval

- P/Princox_noun.json
Description:
Added word princox
> Added word princox

- C/Crunk.json
Description:
Add new word `Crunk`
> Add Crunk word

- H/Hangry.json
Description:
Add new word `Hangry`
> Add Hangry word

- A/Aquifer_noun.json
- A/Arete_noun.json
- A/Atoll_noun.json
- B/Batholith_noun.json
- B/Biota_noun.json
Description:
I have added new 5 words that starts with A and B
> Contribution by #rajputvishwas

- A/Armadillo_noun.json
Description:
Add word `Armadillo`
> Adding word starting with A

- M/Monomaniacal_adjective.json
Added word Monomaniacal to M folder
> Added the verb monomaniacal

- A/Apoptosis.json
Description:
Adding a new word "Apoptosis"
> Adding the word 'Apoptosis'

- I/Indubitable_adjective.json
> Added adjective: Indubitable

- C/Conscience.json
Added a new word in C as Conscience which means 'a person's moral sense of right and wrong, viewed as acting as a guide to one's behaviour '.
> Added new word in C as Conscience

- G/Gadabout_noun.json
Description:
add word `gadabout`
> Adding word Gadabout

- M/Magnanimous_adj.json
> Fidel committed here

- Surprise_Me_Text_To_Audio_CLI/requirements.txt
now supports in windows also :)
Description:
> this installs pywin32 required for pyttsx3 to work

- M/Miscegene_noun.json
> added word Miscegene

- B/Barnstorm.json
> Barnstorm.json

- A/Antidisestablishmentarianism.json
> Add Antidisestablishmentarianism

- Surprise_Me_Text_To_Audio_CLI/README.md
> tested with windows also - it works fine after installing pypiwin32

- P/Palatable.md
> Adding palatable

- H/Hemoglobin.json
Description:
Added a new noun, Hemoglobin.
> Added Hemoglobin

- E/Efflorescence.json
> created new word Efflorescence

- P/Physics.json
Description:
Added word 'Physics'
> Add P word Physics

- D/Durian_noun.json
* Add Durian_noun
* A tropical fruit native to Indonesia and most Southeast Asian nations.
> add Durian_noun

- P/Palate_noun.json
Added the noun "Palate" to the directory of words starting with the letter "p"
> added the noun "Palate" to the word bank

- Z/Zamouse_noun.json
- Z/Zonure_noun.json
- Z/Zygocactus_noun.json
Description:
Add files to Z folder
> Add files to Z folder

- O/Oops.json
> add my changes

- W/Widthless_adjective.json
The Pull Request resolves Issue #696
Description:
Added the word **"Widthless"** to the library.
> Added the word 'Widthless'

- U/Upbraid_verb.json
Added word 'Upbraid' to list of words
> Added new word upbraid

- D/Dapper.json
Description:
Added the word Dapper to the words starting with the letter "D"
> Added Dapper

- P/Piercing_noun.json.txt
> Piercing added

- S/Swag.json
> Creating Swag.json

- A/Arthritis.json
Description:
Added word Arthritis
> Added Arthritis

- D/Determinstic.json
> Added Determinstic

- O/Ouevre.json
> Inventro's changes

- N/Noob_noun.json
The Pull Request adds a definition for "noob"
> Add "Noob"

- T/Tardigrade_noun.json
Adding definition for Tardigrade
> Added Tardigrade

- R/Ragamuffin_noun.json
> add noun ragamuffin

- O/Ornithology.json
The Pull Request resolves Issue #[691]
I've added the word 'Ornithology'.
> Add Ornithology

- G/Gastroenterology.json
The Pull Request resolves Issue #[691]
Description:
I've added the word 'Gastroenterology' along with its definition and figure of speech.
> Added Gastroenterology for #691

- D/Despot_noun.json
Description:
Added the word despot
> Added word Despot

- D/Despotism_noun.json
Description:
Added the word Despotism
> Added word despotism

- V/Vulgo.json
- Z/Zaggle.json
> Added new word Zaggle in Z category

- V/Vulgo.json
- V/Vulgo_adverb.json
- Y/Yaud.json
- Z/Zaggle.json
> Added a new word Yaud in Y

- V/Vulgo.json
- V/Vulgo_adverb.json
- Z/Zaggle.json
> added in a new word Vulgo in V

- V/Vulgo.json
- V/Vulgo_adverb.json
- Z/Zaggle.json
- Z/Zek_noun.json
Added a new word in Zek in The Z
> Added a new word Zek in Z

- V/Vulgo.json
- V/Vulgo_adverb.json
- Y/Yaup_verb.json
- Z/Zaggle.json
- Z/Zek_noun.json
Added A new word Yaup in Y . Yaup is verb
> Added A new word Yaup in Y

- B/Bling.json
> ADD Bling in B

- U/Unintelligently_adverb.json
> Add unintelligently (adverb)

- P/Palazzi.json
> Palazzi.json

- Y/Yahwism.json
> Yahwism.json

- A/Astounding.json
Description:
Added the word "Astounding".
> Adding Astounding word.

- C/Control.json
- S/Semaphore.json
Description:
Added Semaphore(Noun).
> Added Semaphore.json

- S/Skedaddle_verb.json
- X/Xenial_adjective.json
- X/Xylotypography_noun.json
Added words Skedaddle, Xenial and Xylotypograhy
> Add words in S and X

- S/Samurai_noun.json
Description:
Added word samurai
> Add samurai

- D/Doisy_Noun.json
- U/Upsy-daisy_interjection.json
- W/Womanise_verb.json
- W/Wonting_adjective.json
- W/Woodwax_noun.json
The Pull Request resolves Issue #699 , #547 
Add : 
* Woodwax
* Womanise
* Wonting
* Doisy
* Upsy-daisy
> Add Wo files

- A/Aardvark_noun.json
Adds Aardvark to A words folder
> Add Aardvark

- P/Palaeogeography_noun.json
- P/Palaeography_noun.json
- P/Palaeontologist_noun.json
- P/Palaeontology_noun.json
- P/Palette_noun.json
- Palaeogeography
- Palaeography
- Palaeontologist
- Palaeontology
- Palette
> Add P Words

- M/Myriad.json
> Created Myriad Json

- C/Cabal_noun.json
- C/Cabbage_noun.json
- C/Congeal_verb.json
- C/Congenial_adjective.json
- Cabal
- Cabbage
- Congeal
- Congenial
> Add some words beginning with C

- S/Sushi_noun.json
I added a definition of Sushi.
> Add Sushi_noun.json

- T/Tessellate_verb.json
The Pull Request resolves Issue #807 
Description:
> Add Tessellate

- S/Starry_adjective.json
The Pull Request resolves Issue #356
Description:
Add a word `Starry`
> Add word starry :syringe:

- A/Ariel_noun.json
Description:
Add a Word `Ariel`
> Add a noun 'Ariel'

- M/Marlin_noun.json
Description:
Add word `Marlin`.
> Add word marlin :syringe:

- S/Schway.json
> Added word "Schway"

- H/Hector.json
> Added Hector

- C/Circumvallate_adjective.json
- H/Hexyl_noun.json
Description:
Added word Circumvallate
> Added word Circumvallate #627

- K/Knock.json
> Add Tough #121

- C/Commotion.json
The Pull Request references Issue #627
Description:
Added a new word, commotion!
> Add new word Commotion

- C/Cryptic.json
The Pull Request references Issue #627
Description:
Added a new word, `cryptic`!
> Add new word Cryptic

- S/Saudade_noun.json
Added vocabulary entry for the word Saudade
> added entry for Saudade

- P/Pe_noun.json
> Created Pe_noun

- G/Goosy_Adjective.json
The Pull Request resolves Issue #547
Add words ending with "sy"
I create the JSON file for the word "Goosy".
> Fix-issue547: Add word 'Goosy'

- X/Xenomorph.json
Description:
Run as fast as you can...!
> added an alien

- C/Callipygian.json
- S/Saxicolous.json
- S/Sublime.json
Description:
Added a word to the list
> Callipygian

- S/Sublime.json
Description:
Added a word to the list
> Added Sublime to the list under S

- S/Saxicolous.json
- S/Sublime.json
Description:
Added a word to the list
> Saxicolous

- E/Erinaceous_adjective.json
> added definition for erinaceous

- U/Unasinous.json
> Added Unasinous

- S/Stalwart_adjective.json
- S/stalwart_adjective.json
> Add 'Stalwart'

- A/Angina.json
- A/Angina_noun.json
> Added Angina

- C/Concatenation.json
- C/concatenation.json
Description:
This PR adds the word "concatenation".
> Add concatenation

- D/Dork_noun.json
- D/dork_noun.json
> added noun dork

- I/Intercalation_noun.json
> Added Intercalation

- U/Ultrafiltration_noun.json
> fixed mistake

- C/Commit_verb.json
The Pull Request adds a definition to Commit verb
> Adding definition to commit verb

- C/Confound.json
- E/Elevate.json
- E/Eulogy.json
> Added the three words "Elevate", "Confound" and "Eulogy"

- P/Palanquin_noun.json
Description:
Added palanquin (n).
> Adding Palanquin_noun.json

- B/Bilious_adjective.json
- P/Platitudinous_adjective.json
Added 2 new words
-Bilious
-Platitudinous
> Added 'Bilious' and 'Platitudinous'

- H/Hispid_adjective.json
- R/Righteous.json
This Pull Request adds the adjective Righteous
> Added adjective Righteous

- B/Blond.json
New word
The Pull Request added new word
Description:
I added new word
> Added new word Blond

- A/Ayapana_noun.json
- A/Ayont_preposition.json
- A/Ayous_noun.json
- A/Ayre_noun.json
- A/Ayrshire_noun.json
- A/Aythya_noun.json
Description:
A brief description of the addition or edits made.
> added some new words

- E/Entrenched_adjective.json
The Pull Request adds Entrenched word.
Description:
Entrenched is being added
> Added Entrenched

- K/Kaizen.json
> Add the word "Kaizen"

- J/jailson.json
> added myself

- G/gambol_verb.json
> added gambol

- Z/Zeroinon_verb.json
> Zero-in-on verb Added

- N/naboism.json
Description:
hacktober fest task1
> hacktober fest 1

- L/lov.json
> defined love

- Q/Quang_hoang.json
it is first committed. Thanks!
> This commit by Quang

- Z/Zabaione.json
Description:
Addition of the word Zabaione (noun).
> Added the word Zabaione

- Z/Zorro.json
Description:
Definition of a new word 'zorro' added.
> Adding word 'Zorro'

- F/Flummoxed_adjective.json
The Pull Request resolves Issue `Added word Flummoxed in Flummoxed_adjective.json`
Description:
Added word Flummoxed in Flummoxed_adjective.json
> Added word Flummoxed in Flummoxed_adjective.json

- A/Apotheosis_noun.json
The Pull Request resolves Issue #2516
Description:
Added word "Apotheosis"
> Added word "Apotheosis"
